### ISSUE TITLE
Opening another workflow caused an error

### ISSUE THREAD

**Issue by xiaolui12** [komojini/komojini-comfyui-nodes#2]
![微信图片_20240115225256](https://github.com/komojini/komojini-comfyui-nodes/assets/152729445/239ca225-7e70-4c74-9276-6874c78da650)
TypeError: Cannot read properties of undefined (reading 'control_after_generate')
at ComfyNode.<anonymous> (http://127.0.0.1:8188/extensions/komojini-comfyui-nodes/komojini.core.js:823:79)
at object.<computed> (http://127.0.0.1:8188/extensions/komojini-comfyui-nodes/komojini.core.js:19:22)
at nodeType.onNodeCreated (http://127.0.0.1:8188/extensions/core/saveImageExtraOutput.js:25:45)
at Object.createNode (http://127.0.0.1:8188/lib/litegraph.core.js:478:22)
at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2215:38)
at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1323:22)
at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:53:21)
at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1756:15)
at async app.loadGraphData (http://127.0.0.1:8188/extensions/core/undoRedo.js:23:12)

**Comment by komojini** [comment]
You mean opening another workflow by "Load" button?

**Comment by xiaolui12** [comment]
> 您的意思是通过“加载”按钮打开另一个工作流程？

对，我是用[comfyui-workspace-manager](https://github.com/11cafe/comfyui-workspace-manager)这个管理插件打开另一个工作流，然后会导致某些工作流节点全部堆积在左上角同一个点，然后节点链接全部断开，给出的提示就是上面那张图，但很奇怪的是不是所有工作流都这个，只是个别工作流会发生这样的情况。

**Comment by xiaolui12** [comment]
> You mean opening another workflow by "Load" button?
Yes, I used the comfyui workspace manager management plugin to open another workflow, which caused some workflow nodes to pile up at the same point in the upper left corner, and then all node links were broken. The prompt given was the same as the one in the above picture, but it's strange that not all workflows are like this, only a few workflows may experience this situation.
