### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by yuvraj108c** [komojini/komojini-comfyui-nodes#3]
Traceback (most recent call last):
  File "/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/ComfyUI/custom_nodes/komojini-comfyui-nodes/__init__.py", line 1, in <module>
    from .nodes import *
  File "/ComfyUI/custom_nodes/komojini-comfyui-nodes/nodes/__init__.py", line 1, in <module>
    from .video_loaders import YouTubeVideoLoader, UltimateVideoLoader
  File "/ComfyUI/custom_nodes/komojini-comfyui-nodes/nodes/video_loaders.py", line 174, in <module>
    def is_gif(filename: Path | str) -> bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by komojini** [comment]
Thanks for letting me know, I fixed it and pushed

**Comment by yuvraj108c** [comment]
Another issue popped up:

Traceback (most recent call last):
  File "/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/ComfyUI/custom_nodes/komojini-comfyui-nodes/__init__.py", line 1, in <module>
    from .nodes import *
  File "/ComfyUI/custom_nodes/komojini-comfyui-nodes/nodes/__init__.py", line 2, in <module>
    from .image_merger import ImageMerger
  File "/ComfyUI/custom_nodes/komojini-comfyui-nodes/nodes/image_merger.py", line 54, in <module>
    class ImageMerger:
  File "/ComfyUI/custom_nodes/komojini-comfyui-nodes/nodes/image_merger.py", line 102, in ImageMerger
    def get_xy(mark_string: str, height: int, width: int) -> Tuple[int, int] | None:
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

Cannot import /ComfyUI/custom_nodes/komojini-comfyui-nodes module for custom nodes: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

**Comment by komojini** [comment]
Fixed this one too, thanks.
