### ISSUE TITLE
using setter and gettrt error TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by whmc76** [komojini/komojini-comfyui-nodes#9]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 99, in get_output_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

<img width="701" alt="1706198443588" src="https://github.com/komojini/komojini-comfyui-nodes/assets/129386342/d0ff631d-d607-4ba0-b33d-de4099f7b63f">

try image getter or cached getter , the same error

**Comment by komojini** [comment]
This happens when there is no setter node for "supersample". If you can share any workflow for this error, it will be helpful for fixing it.

**Comment by whmc76** [comment]
![image](https://github.com/komojini/komojini-comfyui-nodes/assets/129386342/0cc49b8d-1728-4b84-a4de-f59069671413)
[SVD test.json](https://github.com/komojini/komojini-comfyui-nodes/files/14061945/SVD.test.json)
in this workflow， i want to run two part of video generation and highres fix,

**Comment by komojini** [comment]
You should at least once run the "Setter" node for the key value to use "CachedGetter". Also other getters won't work if the setter node is bypassed or not activated.

**Comment by whmc76** [comment]
> [SVD_test.json](https://github.com/komojini/komojini-comfyui-nodes/files/14064814/SVD_test.json)
> 
> I recommend workflow like this in your case. You can run your workflow one by one using the "Flowbuilder" Node and don't have to bypass unused nodes.

thx,i will try the flowbuilder

**Comment by whmc76** [comment]
> [SVD_test.json](https://github.com/komojini/komojini-comfyui-nodes/files/14064814/SVD_test.json)
> 
> I recommend workflow like this in your case. You can run your workflow one by one using the "Flowbuilder" Node and don't have to bypass unused nodes.

Sorry to bother you, but I have absolutely no idea how to use the two nodes flowbuildergetter and flowbuildersetter. When I try to execute the first group and the second group respectively, the first group can be executed separately, but once the second group starts, the first group will also start executing at the same time
![image](https://github.com/komojini/komojini-comfyui-nodes/assets/129386342/28459b21-f028-40b0-9022-6e7142417496)
[SVD test (1).json](https://github.com/komojini/komojini-comfyui-nodes/files/14066029/SVD.test.1.json)

**Comment by komojini** [comment]
I think it's because your "PreSampling" node's seed setting after generate is "randomize" change it to "fix".

**Comment by whmc76** [comment]
> I think it's because your "PreSampling" node's seed setting after generate is "randomize" change it to "fix".

I completely revised the workflow, but he still executes the second flowbuilder as before, and still executes the previous process again.
If I choose to disable unrelated nodes, I will only turn off the preview image, and other nodes will not be affected.
Also I'm still curious how the flowbuildergetter is used

![image](https://github.com/komojini/komojini-comfyui-nodes/assets/129386342/8cf66fd2-4d5a-4c02-931a-8a9dfaa6da96)
![image](https://github.com/komojini/komojini-comfyui-nodes/assets/129386342/dcf62d3d-4b5d-4c78-a963-586ca05a96d0)
[SVD test.json](https://github.com/komojini/komojini-comfyui-nodes/files/14071726/SVD.test.json)

**Comment by komojini** [comment]
![image](https://github.com/komojini/komojini-comfyui-nodes/assets/118584718/cfd9015f-4011-4031-9482-4d8d750f7690)

Will you try changing the "control_after_generate" part to "fixed"?

**Comment by komojini** [comment]
I usually use rgthree's Seed node.

**Comment by whmc76** [comment]
To be honest, in fact, I just want to use your node to completely replace the rgthree plugin, so that the workflow can install one less plugin.

**Comment by whmc76** [comment]
even i use the seed(rgthree) and fixed 2 sampler seed, it still run all sampler when i queue 2nd flowbuilder

![image](https://github.com/komojini/komojini-comfyui-nodes/assets/129386342/a15bf991-39d7-4d86-964a-0c82afc945b5)
